#!/usr/bin/env python3

import argparse
import local_learning
import logging

logger = logging.getLogger()

from local_learning.models.loopy.search import search_harness

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Run checks on loopy.factory sampled models.')
    parser.add_argument('--verbose', '-v', action='count', default=0)
    args = parser.parse_args()

    if args.verbose == 0:
        logger.setLevel(logging.ERROR)
    elif args.verbose == 1:
        logger.setLevel(logging.INFO)
    elif args.verbose > 1:
        logger.setLevel(logging.DEBUG)

    for _, code, results in search_harness():
        total_score = sum(results) / len(results)
        logger.info('{} got score {} with results {}'.format(code[:200].replace('\n', '\\n'), total_score, results))
